'use client';

import { useCallback, useEffect, useState } from 'react';

type Campaign = { id: string; title: string; message: string; cadence: string; enabled: boolean };
type Metrics = { users: number; totalUsers: number; totalRuns: number; completedRuns: number; activeRuns: number; activeToday: number; completionRate: number };
type Season = { id: string; label: string; clubs: Array<{ id: string; name: string }> };
type RecentRun = { id: string; createdAt: string; completed: boolean; points: number | null; position: number | null; user: { displayName: string; username: string | null } | null };
type PlayerRow = { id: string; rating: number; mainPosition: string; otherPositions: string | null; player: { fullName: string; lastName: string }; clubSeason: { club: { nameRu: string }; season: { label: string } } };

const card = 'rounded-xl border border-[#262626] bg-[#141414] p-4';
export default function AdminPage() {
 const [telegramId, setTelegramId] = useState(''); const [code, setCode] = useState(''); const [codeSent, setCodeSent] = useState(false); const [signedIn, setSignedIn] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
 const [tab, setTab] = useState('overview'); const [metrics, setMetrics] = useState<Metrics | null>(null); const [recentRuns, setRecentRuns] = useState<RecentRun[]>([]); const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [admins, setAdmins] = useState<Array<{ telegramId: string; role: string; status: string }>>([]);
 const [seasons, setSeasons] = useState<Season[]>([]); const [seasonId, setSeasonId] = useState(''); const [clubSeasonId, setClubSeasonId] = useState(''); const [players, setPlayers] = useState<PlayerRow[]>([]);
 const [title, setTitle] = useState(''); const [message, setMessage] = useState(''); const [cadence, setCadence] = useState('weekly'); const [newAdmin, setNewAdmin] = useState('');
 const load = useCallback(async () => {
   const r = await fetch('/api/admin/dashboard'); if (!r.ok) { setSignedIn(false); return; }
   const data = await r.json(); setMetrics(data.metrics); setRecentRuns(data.recentRuns || []); setCampaigns(data.campaigns || []); setSignedIn(true);
   const [access, roster] = await Promise.all([fetch('/api/admin/access'), fetch('/api/admin/rosters')]);
   if (access.ok) setAdmins((await access.json()).admins); if (roster.ok) { const d = await roster.json(); setSeasons(d.seasons); if (!seasonId && d.seasons[0]) setSeasonId(d.seasons[0].id); }
 }, [seasonId]);
 useEffect(() => { void load(); }, [load]);
 useEffect(() => { if (!signedIn || !seasonId) return; const season = seasons.find(s => s.id === seasonId); if (!season) return; setClubSeasonId(season.clubs[0]?.id || ''); }, [signedIn, seasonId, seasons]);
 useEffect(() => { if (!signedIn || !clubSeasonId) return; fetch(`/api/club-seasons/${clubSeasonId}/players`).then(r => r.ok ? r.json() : []).then(d => setPlayers(Array.isArray(d) ? d : d.players || [])).catch(() => setPlayers([])); }, [signedIn, clubSeasonId]);
 async function post(path: string, data: unknown, method = 'POST') { const r = await fetch(path, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || 'Ошибка запроса'); return d; }
 async function requestCode() { setBusy(true); setError(''); try { await post('/api/admin/auth/request', { telegramId }); setCodeSent(true); } catch(e) { setError(e instanceof Error ? e.message : 'Не удалось отправить код'); } finally { setBusy(false); } }
 async function verify() { setBusy(true); setError(''); try { await post('/api/admin/auth/verify', { telegramId, code }); await load(); } catch(e) { setError(e instanceof Error ? e.message : 'Неверный код'); } finally { setBusy(false); } }
 if (!signedIn) return <main className="mx-auto max-w-md p-6 pt-16 text-white"><h1 className="mb-2 text-2xl font-black">Админ-панель 30-0</h1><p className="mb-6 text-sm text-[#9CA3AF]">Войдите по Telegram ID и одноразовому коду от бота.</p><section className={`${card} space-y-3`}><input value={telegramId} onChange={e => setTelegramId(e.target.value)} placeholder="Telegram ID" inputMode="numeric" className="w-full rounded-lg border border-[#333] bg-[#090909] p-3"/>{codeSent && <input value={code} onChange={e => setCode(e.target.value)} placeholder="Код из Telegram" inputMode="numeric" className="w-full rounded-lg border border-[#333] bg-[#090909] p-3"/>}{error && <p className="text-sm text-red-400">{error}</p>}{error.includes('@RPL30_bot') && <a href="https://t.me/RPL30_bot?start=admin_login" target="_blank" rel="noopener noreferrer" className="block w-full rounded-lg border border-[#00C896] p-3 text-center font-semibold text-[#00C896]">Открыть @RPL30_bot и нажать Start</a>}<button disabled={busy} onClick={() => codeSent ? void verify() : void requestCode()} className="w-full rounded-lg bg-[#00C896] p-3 font-bold text-black">{busy ? 'Подождите…' : codeSent ? 'Войти' : 'Получить код в Telegram'}</button></section></main>;
 const tabButton = (id: string, label: string) => <button key={id} onClick={() => setTab(id)} className={`rounded-lg px-3 py-2 text-sm ${tab===id?'bg-[#00C896] text-black':'bg-[#171717] text-[#aaa]'}`}>{label}</button>;
 return <main className="mx-auto max-w-6xl space-y-5 p-4 pb-12 text-white md:p-8"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-[#00C896]">30-0</p><h1 className="text-3xl font-black">Панель управления</h1></div><button onClick={async()=>{await fetch('/api/admin/auth/logout',{method:'POST'});setSignedIn(false)}} className="rounded-lg border border-[#333] px-3 py-2 text-sm">Выйти</button></header><nav className="flex flex-wrap gap-2">{[['overview','Аналитика'],['campaigns','Рассылки'],['rosters','Составы'],['admins','Доступы']].map(([a,b])=>tabButton(a,b))}</nav>
 {tab==='overview' && <><section className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">{[['Пользователи',metrics?.totalUsers],['Активны за сутки',metrics?.activeToday],['Всего игр',metrics?.totalRuns],['Сезонов завершено',metrics?.completedRuns],['Незавершённые игры',metrics?.activeRuns],['Завершение сезона',`${metrics?.completionRate ?? 0}%`]].map(([label,value])=><div className={card} key={String(label)}><div className="text-2xl font-black text-[#00C896]">{value ?? '—'}</div><div className="text-xs text-[#999]">{label}</div></div>)}</section><section className={card}><h2 className="mb-3 font-bold">Последние игры по пользователям</h2><div className="space-y-2">{recentRuns.map(r=><div key={r.id} className="grid grid-cols-[1fr_auto_auto] gap-3 border-b border-[#292929] py-2 text-sm"><span>{r.user?.username ? `@${r.user.username}` : r.user?.displayName || 'Гость'}</span><span>{r.completed ? `${r.points ?? 0} очков` : 'В процессе'}</span><span>{r.position ? `${r.position}-е место` : '—'}</span></div>)}</div></section></>}
 {tab==='campaigns' && <section className={`${card} space-y-4`}><div><h2 className="text-xl font-bold">Триггерные рассылки</h2><p className="text-xs text-[#999]">Рассылки уходят пользователям с включёнными уведомлениями, которые запускали бота. Отправка идёт в 12:00 по Москве.</p></div><div className="grid gap-2 md:grid-cols-3"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Название кампании" className="rounded-lg bg-[#090909] p-3"/><select value={cadence} onChange={e=>setCadence(e.target.value)} className="rounded-lg bg-[#090909] p-3"><option value="daily">Ежедневно</option><option value="weekly">Еженедельно</option><option value="monthly">Ежемесячно</option><option value="return">Возврат после 7 дней</option></select><label className="flex items-center gap-2 rounded-lg bg-[#090909] p-3 text-sm"><input id="campaign-enabled" type="checkbox" className="accent-[#00C896]"/>Включить сразу</label></div><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Текст сообщения" rows={3} className="w-full rounded-lg bg-[#090909] p-3"/><button onClick={async()=>{try{await post('/api/admin/campaigns',{title,message,cadence,enabled:(document.getElementById('campaign-enabled') as HTMLInputElement)?.checked});setTitle('');setMessage('');await load()}catch(e){setError(e instanceof Error?e.message:'Ошибка')}}} className="rounded-lg bg-[#00C896] px-4 py-2 font-bold text-black">Создать кампанию</button><div className="space-y-2">{campaigns.map(c=><article key={c.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-[#292929] p-3"><div><strong>{c.title}</strong><p className="text-xs text-[#999]">{c.cadence} · {c.enabled?'включена':'выключена'}</p></div><div className="flex gap-2"><button onClick={async()=>{await post('/api/admin/campaigns',{...c,enabled:!c.enabled},'POST');await load()}} className="rounded border border-[#444] px-3 py-1 text-xs">{c.enabled?'Пауза':'Включить'}</button><button onClick={async()=>{await post('/api/admin/campaigns',{id:c.id},'DELETE');await load()}} className="rounded border border-red-900 px-3 py-1 text-xs text-red-300">Удалить</button></div></article>)}</div></section>}
 {tab==='rosters' && <section className={`${card} space-y-3`}><h2 className="text-xl font-bold">Обновление составов</h2><div className="flex flex-wrap gap-2"><select value={seasonId} onChange={e=>setSeasonId(e.target.value)} className="rounded bg-[#090909] p-2">{seasons.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><select value={clubSeasonId} onChange={e=>setClubSeasonId(e.target.value)} className="rounded bg-[#090909] p-2">{seasons.find(s=>s.id===seasonId)?.clubs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="space-y-2">{players.map(p=><div key={p.id} className="grid grid-cols-[1fr_70px_90px_90px] items-center gap-2 rounded-lg bg-[#0b0b0b] p-2 text-xs"><span>{p.player.lastName} · {p.player.fullName}</span><input aria-label="Рейтинг" type="number" min="1" max="100" defaultValue={p.rating} id={`rating-${p.id}`} className="w-full rounded bg-[#222] p-2"/><input aria-label="Основная позиция" defaultValue={p.mainPosition} id={`main-${p.id}`} className="w-full rounded bg-[#222] p-2"/><button onClick={async()=>{await post('/api/admin/rosters',{id:p.id,rating:Number((document.getElementById(`rating-${p.id}`) as HTMLInputElement).value),mainPosition:(document.getElementById(`main-${p.id}`) as HTMLInputElement).value,otherPositions:p.otherPositions||''},'PATCH')}} className="rounded bg-[#00C896] px-2 py-2 font-bold text-black">Сохранить</button></div>)}</div></section>}
 {tab==='admins' && <section className={`${card} space-y-4`}><h2 className="text-xl font-bold">Доступ к админке</h2><p className="text-sm text-[#999]">Новый администратор должен запустить бота и подтвердить приглашение. Только владелец может выдавать доступ.</p><div className="flex gap-2"><input value={newAdmin} onChange={e=>setNewAdmin(e.target.value)} placeholder="Telegram ID" className="min-w-0 flex-1 rounded-lg bg-[#090909] p-3"/><button onClick={async()=>{try{await post('/api/admin/access',{telegramId:newAdmin});setNewAdmin('');await load()}catch(e){setError(e instanceof Error?e.message:'Ошибка')}}} className="rounded-lg bg-[#00C896] px-4 font-bold text-black">Пригласить</button></div>{error&&<p className="text-sm text-red-300">{error}</p>}<div className="space-y-2">{admins.map(a=><div key={a.telegramId} className="flex items-center justify-between rounded-lg border border-[#292929] p-3"><span>{a.telegramId} · {a.role} · {a.status}</span>{a.role!=='owner'&&<button onClick={async()=>{await post('/api/admin/access',{telegramId:a.telegramId},'DELETE');await load()}} className="text-sm text-red-300">Отозвать</button>}</div>)}</div></section>}
 </main>;
}
